# Generated by Django 3.2.6 on 2021-10-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='омлет', max_length=50, verbose_name='Название блюда')),
                ('item_description', models.TextField(default='Омлет из пяти яиц', max_length=250, verbose_name='Описание блюда')),
                ('item_composition', models.TextField(default='Яйца, молоко', max_length=250, verbose_name='Состав блюда')),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Масса нетто')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена блюда')),
                ('item_calories', models.DecimalField(decimal_places=2, default=100, max_digits=9, max_length=10, verbose_name='Калорийность')),
                ('item_image', models.ImageField(upload_to='menu', verbose_name='Фотография блюда')),
                ('milk_added', models.BooleanField(default=False, verbose_name='Молоко в составе')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
