# Generated by Django 4.1.10 on 2023-08-19 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('first_name', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default=123, max_length=20)),
                ('email', models.EmailField(default='email@email.com', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Meal name')),
                ('item_en', models.CharField(max_length=50, null=True, verbose_name='Meal name')),
                ('item_uk', models.CharField(max_length=50, null=True, verbose_name='Meal name')),
                ('item_pl', models.CharField(max_length=50, null=True, verbose_name='Meal name')),
                ('category', models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, verbose_name='Category')),
                ('label', models.CharField(blank=True, choices=[('', ''), ('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label')),
                ('item_description', models.CharField(max_length=150, verbose_name='Meal description')),
                ('item_description_en', models.CharField(max_length=150, null=True, verbose_name='Meal description')),
                ('item_description_uk', models.CharField(max_length=150, null=True, verbose_name='Meal description')),
                ('item_description_pl', models.CharField(max_length=150, null=True, verbose_name='Meal description')),
                ('item_composition', models.CharField(max_length=150, verbose_name='Ingredients')),
                ('item_composition_en', models.CharField(max_length=150, null=True, verbose_name='Ingredients')),
                ('item_composition_uk', models.CharField(max_length=150, null=True, verbose_name='Ingredients')),
                ('item_composition_pl', models.CharField(max_length=150, null=True, verbose_name='Ingredients')),
                ('item_weight', models.FloatField(verbose_name='Net weight')),
                ('item_price', models.FloatField(default=100.0, verbose_name='Meal price')),
                ('item_discount', models.FloatField(blank=True, null=True, verbose_name='Discounted price')),
                ('item_calories', models.IntegerField(default=100, verbose_name='Calories')),
                ('item_image', models.ImageField(upload_to='goods', verbose_name='Meal image')),
                ('milk_added', models.BooleanField(default=False, verbose_name='Milk components added')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.menuitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('checkout_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.checkoutaddress')),
                ('items', models.ManyToManyField(to='delivery.orderitem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
