# Generated by Django 3.2.6 on 2021-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='item_image',
            field=models.ImageField(upload_to='goods', verbose_name='Фотография блюда'),
        ),
    ]
