# Generated by Django 4.1.4 on 2023-01-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_auto_20211101_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_price',
            field=models.FloatField(default=100.0, verbose_name='Цена блюда'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_weight',
            field=models.FloatField(verbose_name='Масса нетто'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='title',
            field=models.CharField(default='Название блюда', max_length=50, verbose_name='Название блюда'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.menuitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('checkout_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.checkoutaddress')),
                ('items', models.ManyToManyField(to='delivery.orderitem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
