# Generated by Django 4.1.4 on 2023-01-22 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_title_menuitems_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowMenuItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.orderitem')),
            ],
            bases=(django.views.generic.list.ListView, 'delivery.orderitem'),
        ),
    ]
