# Generated by Django 4.1.4 on 2023-01-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_menuitems_item_discount_delete_showmenuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='zip',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=25),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='first_name',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
