# Generated by Django 4.1.4 on 2023-02-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_rename_zip_checkoutaddress_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('B', 'Сніданок'), ('LC', 'Обід'), ('SN', 'Заїдка'), ('D', 'Напої'), ('SD', 'Салати'), ('DS', 'Десерти')], default='B', max_length=2, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Найменування страви'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_calories',
            field=models.IntegerField(default=100, verbose_name='Калорії'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_composition',
            field=models.CharField(max_length=150, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_description',
            field=models.CharField(max_length=150, verbose_name='Опис страви'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Знижка'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_image',
            field=models.ImageField(upload_to='goods', verbose_name='Зображення страви'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_price',
            field=models.FloatField(default=100.0, verbose_name='Ціна блюда'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_weight',
            field=models.FloatField(verbose_name='Вага нето'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'Новина'), ('BS', 'Найкращий вибір!')], max_length=2, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Містить молоко'),
        ),
    ]
