# Generated by Django 4.1.4 on 2023-02-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_menuitems_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category_en',
            field=models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category_pl',
            field=models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category_uk',
            field=models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_composition_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_composition_pl',
            field=models.CharField(max_length=150, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_composition_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Meal description'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_description_pl',
            field=models.CharField(max_length=150, null=True, verbose_name='Meal description'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_description_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Meal description'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Meal name'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_pl',
            field=models.CharField(max_length=50, null=True, verbose_name='Meal name'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Meal name'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='label_en',
            field=models.CharField(blank=True, choices=[('', ''), ('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='label_pl',
            field=models.CharField(blank=True, choices=[('', ''), ('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='label_uk',
            field=models.CharField(blank=True, choices=[('', ''), ('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('LC', 'Lunch'), ('SN', 'Snack'), ('D', 'Drinks'), ('SD', 'Salads'), ('DS', 'Desserts')], default='B', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Meal name'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_calories',
            field=models.IntegerField(default=100, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_composition',
            field=models.CharField(max_length=150, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_description',
            field=models.CharField(max_length=150, verbose_name='Meal description'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Discounted price'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_image',
            field=models.ImageField(upload_to='goods', verbose_name='Meal image'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_price',
            field=models.FloatField(default=100.0, verbose_name='Meal price'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_weight',
            field=models.FloatField(verbose_name='Net weight'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='label',
            field=models.CharField(blank=True, choices=[('', ''), ('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Milk components added'),
        ),
    ]
