# Generated by Django 4.1.4 on 2023-02-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_menuitems_options_menuitems_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='category_pl',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='category_uk',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='label_pl',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='label_uk',
        ),
    ]
