# Generated by Django 3.2.6 on 2021-10-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='avatars', verbose_name='Аватар пользователя')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('undefined', 'Не знаю')], max_length=10, verbose_name='Ваш пол')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон пользователя')),
                ('agreement', models.BooleanField(default='True', verbose_name='Согласие на обработку персональных данных')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
