# Generated by Django 3.2.6 on 2021-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Веган', max_length=20, verbose_name='Ваше имя'),
        ),
    ]
