# Generated by Django 4.1.10 on 2023-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Your email address')),
                ('subject', models.CharField(max_length=100, verbose_name='Email subject')),
                ('message', models.TextField(max_length=1000, verbose_name='Email text')),
            ],
        ),
    ]
