# Generated by Django 3.2.9 on 2021-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20211106_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='fridge_life',
        ),
        migrations.RemoveField(
            model_name='breakfast',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='breakfast',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='breakfast',
            name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='french_toasts',
            name='fridge_life',
        ),
        migrations.RemoveField(
            model_name='french_toasts',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='french_toasts',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='french_toasts',
            name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='fridge_life',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='fridge_life',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='fridge_life',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='in_box',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='shelf_life',
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Есть ли молоко в составе'),
        ),
        migrations.AlterField(
            model_name='french_toasts',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Есть ли молоко в составе'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Есть ли молоко в составе'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Есть ли молоко в составе'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='milk_added',
            field=models.BooleanField(default=False, verbose_name='Есть ли молоко в составе'),
        ),
    ]
