# Generated by Django 3.2.9 on 2021-11-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20211106_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='french_toasts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salads',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='description',
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='calories',
            field=models.IntegerField(default=100, verbose_name='Калорийность, Ккал'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='composition',
            field=models.TextField(default='Состав', max_length=250, verbose_name='Состав (описание) блюда'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Масса нетто, гр.'),
        ),
        migrations.AlterField(
            model_name='french_toasts',
            name='calories',
            field=models.IntegerField(default=100, verbose_name='Калорийность, Ккал'),
        ),
        migrations.AlterField(
            model_name='french_toasts',
            name='composition',
            field=models.TextField(default='Состав', max_length=250, verbose_name='Состав (описание) блюда'),
        ),
        migrations.AlterField(
            model_name='french_toasts',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Масса нетто, гр.'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='calories',
            field=models.IntegerField(default=100, verbose_name='Калорийность, Ккал'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='composition',
            field=models.TextField(default='Состав', max_length=250, verbose_name='Состав (описание) блюда'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Масса нетто, гр.'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='calories',
            field=models.IntegerField(default=100, verbose_name='Калорийность, Ккал'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='composition',
            field=models.TextField(default='Состав', max_length=250, verbose_name='Состав (описание) блюда'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Масса нетто, гр.'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='calories',
            field=models.IntegerField(default=100, verbose_name='Калорийность, Ккал'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='composition',
            field=models.TextField(default='Состав', max_length=250, verbose_name='Состав (описание) блюда'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Масса нетто, гр.'),
        ),
    ]
