# Generated by Django 3.2.9 on 2021-11-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20211106_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'verbose_name': 'Завтрак', 'verbose_name_plural': 'Завтраки'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар для корзины', 'verbose_name_plural': 'Товары для корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='french_toasts',
            options={'verbose_name': 'Тост', 'verbose_name_plural': 'Тосты'},
        ),
        migrations.AlterModelOptions(
            name='lunch',
            options={'verbose_name': 'Обед', 'verbose_name_plural': 'Обеды'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'Перекус', 'verbose_name_plural': 'Перекусы'},
        ),
        migrations.AddField(
            model_name='breakfast',
            name='some',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочие характеристики'),
        ),
        migrations.AddField(
            model_name='snack',
            name='some_new',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Еще характеристики'),
        ),
    ]
